### ISSUE TITLE
analisis app

### ISSUE THREAD

**Issue by salathiel1999** [SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-vo#1]
[Reporte de app .pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-analisis-de-app-de-realidad-aumentada-team-vo/files/14314510/Reporte.de.app.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
